### ISSUE TITLE
do not use unwanted dependencies 

### ISSUE THREAD

**Issue by Jaswanth-S** [arpmazu1/SpringBoot-App#8]
<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<version>1.4.199</version>

		</dependency>

found in mongodb

**Comment by arpmazu1** [comment]
depedency removed

**Comment by arpmazu1** [comment]
dependency removed

**Comment by arpmazu1** [comment]
dependency removed
